name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Echo "Start"
        run: echo "Start CI/CD"

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests # Ensure the tests job completes before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy MT School
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            echo "Changing directory to the deployment path"
            cd ${{ secrets.REMOTE_PATH }}
            echo "Pulling the latest changes from the main branch"
            git pull origin main
            echo "Running database migrations"
            php artisan migrate --force --seed
            echo "Checking if composer.json was modified"
            if git diff --name-only HEAD^ composer.json | grep composer.json; then
              echo "composer.json modified, running composer update"
              yes | composer2 update
            else
              echo "No changes in composer.json, skipping composer update"
            fi
            echo "Clearing and optimizing cache"
            php artisan optimize:clear
