name: Laravel CI/CD (Hostinger)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Echo "Start CI/CD"
        run: echo "Start CI/CD Pipeline"

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: |
          composer install

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .
          server-dir: /public_html # Adjust this path based on your server structure

      - name: Post-Deployment Commands (Optional)
        run: |
          echo "Running Laravel commands on the server"
          php artisan migrate --force
          php artisan optimize
          php artisan serve &
